export const PRODUCT_TYPE_VOUCHER = 'VOUCHER';
export const PRODUCT_TYPE_BENEFIT = 'BENEFIT';
export const PRODUCT_TYPE_TOURISM = 'TOURISM';
export const ACCEPTANCE_TYPE_AUTO = 'auto';
export const ACCEPTANCE_TYPE_MANUAL = 'manual';

export const CODES_VISIBILITY_NEVER = 'NEVER';
export const CODES_VISIBILITY_ALWAYS = 'ALWAYS';
export const CODES_VISIBILITY_CUSTOM = 'IF_CODES_QUANTITY_EQUAL_OR_LESS';

export const CODES_VISIBILITY_DEFAULT_VALUES = [CODES_VISIBILITY_ALWAYS, CODES_VISIBILITY_NEVER, CODES_VISIBILITY_CUSTOM];
