import {
  catalogCategoryPermissionRead,
  catalogProductPermissionRead,
  cmsDocumentPermissionRead,
  cmsDocumentPermissionWrite,
  companyCompanyPermissionRead,
  configurationConfigurationPermissionRead,
  dictionaryDictionaryPermissionRead,
  employeeEmployeePermissionRead,
  employeeEmployeePermissionWrite,
  operatorOperatorPermissionRead,
  companyTokenPermissionRead,
  ssoIpAddressRestrictionPermissionRead,
  // subscriptionSubscriptionPermissionWrite,
  tourismTourismAttributePermissionRead,
  tourismTourismObjectPermissionRead,
  // translationTranslateCmsPermissionWrite,
  translationTranslateSimplePermissionWrite,
  translationTranslationScopePermissionRead,
  subscriptionActiveFormPermissionRead,
  agreementAgreementPermissionRead,
  notificationAppMessagePermissionRead,
  subscriptionBenefitCategoryPermissionRead, subscriptionEmployeeSubscriptionItemAccept,
} from '../../utils/RoleBasedSecurity/permissions';

export const MainNav = [
  {
    icon: 'pe-7s-diamond',
    label: 'Katalog produktów',
    to: '/product-catalog',
    id: 'productCatalog',
    content: [
      {
        icon: 'pe-7s-diamond',
        label: 'Lista produktów',
        to: '/product-catalog/products',
        id: 'productCatalogList',
        aclKey: catalogProductPermissionRead,
      },
      {
        label: 'Kategorie biznesowe',
        to: '/product-catalog/business-category',
        id: 'businessCategory',
        aclKey: catalogCategoryPermissionRead,
        icon: 'pe-7s-network',
      },
      {
        label: 'Kategorie abonamentowe',
        to: '/product-catalog/subscription-category',
        id: 'subscriptionCategory',
        aclKey: subscriptionBenefitCategoryPermissionRead,
        icon: 'pe-7s-network',
      },
    ],
  },
  {
    icon: 'pe-7s-shuffle',
    label: 'Lista dostawców',
    to: '/suppliers',
    id: 'suppliers',
    aclKey: tourismTourismObjectPermissionRead,
    isAnchor: true,
  },
  {
    label: 'Turystyka',
    to: '/tourism',
    id: 'tourism',
    icon: 'pe-7s-map',
    content: [
      {
        label: 'Lista obiektów',
        to: '/tourism/objects',
        id: 'tourismListOfObjects',
        aclKey: tourismTourismObjectPermissionRead,
        tileIcon: 'pe-7s-home',
      },
      {
        label: 'Lista dostawców',
        to: '/tourism/suppliers',
        id: 'tourismListOfSuppliers',
        aclKey: tourismTourismObjectPermissionRead,
        tileIcon: 'pe-7s-box2',
      },
      {
        label: 'Zarządzanie atrybutami filtrowania',
        to: '/tourism/managing-filtering-attributes',
        id: 'tourismManagingFilteringAttributes',
        aclKey: tourismTourismAttributePermissionRead,
        tileIcon: 'pe-7s-edit',
      },
    ],
  },
  {
    icon: 'pe-7s-id',
    label: 'Firma',
    id: 'company',
    to: '/company',
    content: [
      {
        label: 'Lista firm',
        to: '/company/list',
        id: 'companyList',
        aclKey: companyCompanyPermissionRead,
        tileIcon: 'pe-7s-id',
      },
      {
        label: 'Lista pracowników',
        to: '/company/employee-list',
        id: 'employeeList',
        aclKey: employeeEmployeePermissionRead,
        tileIcon: 'pe-7s-users',
      },
      {
        icon: 'pe-7s-download',
        label: 'SFTP - Import pracowników',
        to: '/import-sftp',
        id: 'importSftp',
        aclKey: employeeEmployeePermissionWrite,
      },
    ],
  },
  {
    icon: 'pe-7s-tools',
    label: 'Administracja',
    id: 'administration',
    to: '/administration',
    content: [
      {
        label: 'Parametry konfiguracyjne',
        to: '/administration/configuration',
        id: 'configuration',
        aclKey: configurationConfigurationPermissionRead,
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Słowniki',
        to: '/administration/dictionary',
        id: 'dictionary',
        aclKey: dictionaryDictionaryPermissionRead,
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Konfiguracja adresów IP',
        to: '/administration/ip-security',
        id: 'ipSecurity',
        aclKey: ssoIpAddressRestrictionPermissionRead,
        tileIcon: 'pe-7s-unlock',
      },
    ],
  },
  {
    icon: 'pe-7s-user',
    label: 'Operatorzy MB',
    to: '/user',
    id: 'user',
    content: [
      {
        tileIcon: 'pe-7s-user',
        label: 'Lista operatorów',
        to: '/user/operator',
        id: 'userOperatorList',
        aclKey: operatorOperatorPermissionRead,
      },
      {
        tileIcon: 'pe-7s-users',
        label: 'Lista ról',
        to: '/user/role',
        id: 'userGroupList',
        aclKey: operatorOperatorPermissionRead,
      },
    ],
  },
  {
    icon: 'pe-7s-box2',
    label: 'CMS',
    to: '/cms/management',
    isAnchor: true,
    id: 'cms',
    aclKey: cmsDocumentPermissionRead,
  },
  {
    icon: 'pe-7s-note2',
    label: 'Formularze aktywne',
    to: '/active-forms',
    id: 'activeForms',
    aclKey: subscriptionActiveFormPermissionRead,
  },
  {
    icon: 'pe-7s-graph2',
    label: 'Raporty',
    id: 'report',
    to: '/report',
    content: [
      {
        label: 'Raporty',
        to: '/report/predefined_reports',
        id: 'new_report',
        // aclKey: 'new_report',
        tileIcon: 'pe-7s-graph1',
      },
      {
        label: 'Archiwum',
        to: '/report/archive',
        id: 'archive',
        // aclKey: 'archive',
        tileIcon: 'pe-7s-chat',
      },
      {
        label: 'Aktywne wysyłki',
        to: '/report/subscriptions',
        id: 'subscriptions',
        // aclKey: 'subscriptions',
        tileIcon: 'pe-7s-edit',
      },
    ],
  },
  {
    icon: 'pe-7s-check',
    label: 'Zgody',
    to: '/agreements',
    id: 'agreements',
    aclKey: agreementAgreementPermissionRead,
    isAnchor: true,
  },
  {
    icon: 'pe-7s-comment',
    label: 'Powiadomienia',
    id: 'notification',
    to: '/notification',
    content: [
      {
        label: 'Wiadomości wewnątrzsystemowe',
        to: '/notification/app-messages',
        id: 'appMessages',
        aclKey: notificationAppMessagePermissionRead,
        tileIcon: 'pe-7s-chat',
      },
    ],
  },
  {
    icon: 'pe-7s-notebook',
    label: 'Tłumaczenia',
    id: 'translate',
    to: '/translate',
    content: [
      {
        label: 'Tłumaczenia interfejsu',
        to: '/translate/interface',
        id: 'translateInterface',
        aclKey: translationTranslateSimplePermissionWrite,
        tileIcon: 'pe-7s-monitor',
      },
      {
        label: 'Tłumaczenia wartości prostych',
        to: '/translate/simple',
        id: 'translateSimple',
        aclKey: translationTranslateSimplePermissionWrite,
        tileIcon: 'pe-7s-display1',
      },
      // {
      //   label: 'Tłumaczenia opisów',
      //   to: '/translate/description',
      //   id: 'translateDescription',
      //   aclKey: translationTranslateCmsPermissionWrite,
      //   tileIcon: 'pe-7s-display2',
      // },
      {
        label: 'Zakresy tłumaczeń',
        to: '/translate/scopes',
        id: 'translateScopes',
        aclKey: translationTranslationScopePermissionRead,
        tileIcon: 'pe-7s-albums',
      },
    ],
  },
  {
    icon: 'pe-7s-download',
    label: 'Importy',
    id: 'imports',
    to: '/imports',
    content: [
      {
        label: 'Import dokumentów CMS',
        to: '/imports/cms',
        id: 'importCms',
        aclKey: cmsDocumentPermissionWrite,
        tileIcon: 'pe-7s-config',
      },
    ],
  },
  {
    icon: 'pe-7s-display2',
    label: 'Standardy',
    id: 'standards',
    to: '/standards',
    content: [
      {
        label: 'Grid filtrowalny js',
        to: '/standards/grid/filtrable-js',
        id: 'gridFiltrerableJs',
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Grid filtrowalny backend',
        to: '/standards/grid/filtrable-backend',
        id: 'gridFiltrerableBackend',
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Formularze',
        to: '/standards/forms',
        id: 'forms',
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Zakładki (proste)',
        to: '/standards/tabs/simple',
        id: 'tabsSimple',
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Zakładki (z zapamiętywaniem)',
        to: '/standards/tabs/with-memo',
        id: 'tabsWithMemo',
        tileIcon: 'pe-7s-config',
      },
      {
        label: 'Zakładki boczne',
        to: '/standards/tabs/sidebar',
        id: 'tabsSidebar',
        tileIcon: 'pe-7s-config',
      },
    ],
  },
];

export const AhrMainNav = [
  {
    icon: 'pe-7s-user',
    label: 'Pracownicy',
    to: '/ahr/employees',
    isAnchor: true,
    aclKey: employeeEmployeePermissionRead,
    id: 'companyEmployee',
  },
  {
    label: 'Benefity oczekujące',
    icon: 'pe-7s-cup',
    to: '/ahr/pending-benefits',
    aclKey: subscriptionEmployeeSubscriptionItemAccept,
    id: 'pendingBenefits',
  },
  {
    label: 'Imprezy firmowe',
    icon: 'pe-7s-sun',
    to: '/ahr/company-party',
    aclKey: employeeEmployeePermissionRead,
    id: 'companyParty',
  },
  {
    icon: 'pe-7s-graph2',
    label: 'Raporty',
    to: '/ahr/report',
    id: 'report',
    content: [
      {
        label: 'Raporty',
        to: '/ahr/report/predefined_reports',
        id: 'new_report',
        // aclKey: 'new_report',
        tileIcon: 'pe-7s-graph1',
      },
      {
        label: 'Archiwum',
        to: '/ahr/report/archive',
        id: 'archive',
        // aclKey: 'archive',
        tileIcon: 'pe-7s-chat',
      },
      {
        label: 'Aktywne wysyłki',
        to: '/ahr/report/subscriptions',
        id: 'subscriptions',
        // aclKey: 'subscriptions',
        tileIcon: 'pe-7s-edit',
      },
    ],
  },
  {
    icon: 'pe-7s-comment',
    label: 'Powiadomienia',
    id: 'notification',
    to: '/ahr/notification',
    content: [
      {
        label: 'Wiadomości wewnątrzsystemowe',
        to: '/ahr/notification/app-messages',
        id: 'appMessages',
        aclKey: notificationAppMessagePermissionRead,
        tileIcon: 'pe-7s-chat',
      },
    ],
  },
  {
    icon: 'pe-7s-unlock',
    label: 'Dostępy',
    id: 'access',
    acl: companyTokenPermissionRead,
    to: '/ahr/access',
  },
];
