/* eslint-disable import/prefer-default-export */
export const mockData = [
  {
    supplierId: '1',
    city: 'Wrocław',
    name: 'Pyszne.pl',
    benefitsAmount: 2,
    object: 'Sklep wielobranżowy',
    industry: 'Sport',
    checkbox: false,
  },
  {
    supplierId: '2',
    city: 'Gdańsk',
    name: 'Agencja Sport',
    benefitsAmount: 23,
    object: 'Kino',
    industry: 'Sport',
    checkbox: false,
  },
  {
    supplierId: '3',
    city: 'Wrocław',
    name: 'Pewex sp z.o.o.',
    object: 'Pensjonat',
    industry: 'Sport',
    benefitsAmount: 22,
    checkbox: false,
  },
  {
    supplierId: '4',
    city: 'Wrocław',
    name: 'Budimex sp. z o.o.',
    industry: 'Sport',
    object: 'Teatr',
    benefitsAmount: 27,
    checkbox: false,
  },
  {
    supplierId: '5',
    city: 'Wrocław',
    name: 'Organizacja Orzeł\t',
    industry: 'Rekreacja',
    object: 'Muzeum',
    benefitsAmount: 52,
    checkbox: false,
  },
  {
    supplierId: '6',
    city: 'Gdańsk',
    name: 'Organizacja Laser',
    object: 'Park rozrywki',
    industry: 'Kultura',
    benefitsAmount: 2,
    checkbox: false,
  },
  {
    supplierId: '7',
    city: 'Wrocław',
    name: 'Grupa Fauna',
    object: 'Hostel',
    industry: 'Rekreacja',
    benefitsAmount: 2,
    checkbox: false,
  },
  {
    supplierId: '8',
    city: 'Wrocław',
    name: 'Związek Skowronek',
    industry: 'Kultura',
    object: 'Supermarket',
    benefitsAmount: 2,
    checkbox: false,
  },
  {
    supplierId: '9',
    city: 'Wrocław',
    name: 'Grupa Bankiet',
    benefitsAmount: 2,
    object: 'Bar',
    industry: 'Kultura',
    checkbox: false,
  },
  {
    supplierId: '10',
    city: 'Wrocław',
    benefitsAmount: 0,
    object: 'Klub',
    name: 'Grupa Dom',
    industry: 'Rekreacja',
    checkbox: false,
  },
];
